name: Z-Blog 全栈项目自动化部署

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ██ 代码库初始化 █████████████████████████████████
    - name: 拉取代码仓库
      uses: actions/checkout@v4

    # ██ 前端构建环境配置 █████████████████████████████████
    - name: 配置 Node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
        cache-dependency-path: './vue-blog-project/package.json'  # 明确子目录缓存路径:ml-citation{ref="5,8" data="citationList"}

    # - name: 验证依赖锁文件状态
    #   working-directory: ./vue-blog-project
    #   run: |
    #     if [ ! -f "package-lock.json" ] && [ ! -f "yarn.lock" ]; then
    #       echo "紧急错误: 前端项目缺少依赖锁文件!"
    #       exit 1
    #     fi
    #     ls -lh package*.json  # 显示文件详细信息:ml-citation{ref="4,6" data="citationList"}

    # ██ 前端依赖安装与构建 █████████████████████████████████   
    - name: 安装前端依赖
      working-directory: ./vue-blog-project
      run: pnpm ci --legacy-peer-deps  # 严格依据 lockfile 安装:ml-citation{ref="4,5" data="citationList"}

    - name: 编译生产环境代码
      working-directory: ./vue-blog-project
      run: |
        npm run build
        du -sh dist  # 输出构建产物体积验证:ml-citation{ref="4" data="citationList"}

    # ██ 服务器端部署流程 █████████████████████████████████
    - name: 配置 SSH 安全通道
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts:ml-citation{ref="3,7" data="citationList"}

    - name: 智能文件同步
      run: |
        rsync -avz --progress \
          --exclude=.git \
          --exclude=node_modules \
          --include="vue-blog-project/dist/**" \
          -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }}" \
          ./ \
          ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/var/www/z-blog/:ml-citation{ref="4,8" data="citationList"}

    - name: 服务热更新
      run: |
        ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }} \
          ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
          "sudo systemctl reload nginx && pm2 restart all":ml-citation{ref="3" data="citationList"}
