name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 拉取代码到 $GITHUB_WORKSPACE

    - name: Debug - List repository files
      run: |
        echo "仓库文件列表："
        ls -la $GITHUB_WORKSPACE  # 确认仓库文件已拉取

    - name: Sync files to Server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "开始同步文件到服务器..."
          # 强制删除目标目录残留文件（谨慎操作）
          ssh -i "$HOME/.ssh/github_actions_key" \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
            "rm -rf /www/wwwroot/default/*"
          
          # 正确的 rsync 方向：本地仓库 -> 服务器
          rsync -avz --progress --delete \
            -e "ssh -i $HOME/.ssh/github_actions_key" \
            "$GITHUB_WORKSPACE/" \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/default/
          
          echo "同步完成！"
