name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sync files via Rsync
      uses: easingthemes/ssh-deploy@v4
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        KEY_NAME: "github_actions_key"  # 添加此行，自定义密钥文件名
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ${{ secrets.SSH_USERNAME }}
        REMOTE_PORT: ${{ secrets.SSH_PORT }}
        SOURCE: "./"
        TARGET: "/www/wwwroot/default"
        ARGS: "-avz --delete"
        DEBUG: "true"
        SSH_DEBUG_ARGS: "-vvv"
