name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies and build (适配 pnpm/npm)
      working-directory: vue-blog-project  # 指定在项目子目录操作
      run: |
        # 优先尝试使用 pnpm，若不存在则回退到 npm
        if command -v pnpm &> /dev/null; then
          pnpm install
        else
          npm install
        fi
        # 执行构建命令（假设 package.json 中定义了 build 脚本）
        npm run build

    - name: Debug - Show build output
      run: ls -la vue-blog-project/dist  # 确认构建产物存在

    - name: Setup SSH Environment
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
        chmod 600 ~/.ssh/github_actions_key
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Install Rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Sync Build Files via Rsync
      run: |
        rsync -avz --progress --delete \
          --exclude='node_modules' \         # 排除 node_modules
          --exclude='.git' \                 # 可选：排除 git 目录
          -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
          vue-blog-project/dist/ \           # 同步构建后的 dist 目录
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/default/
