name: CI/CD with npm

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ███████ 阶段1：基础设置 ███████
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'  # 强制使用npm缓存:ml-citation{ref="3" data="citationList"}
          cache-dependency-path: '**/package-lock.json'  # 明确指定npm锁文件

      # ███████ 阶段2：依赖处理 ███████
      - name: 删除pnpm锁文件（可选）
        run: rm -f pnpm-lock.yaml  # 防止CI混淆

      - name: 安装依赖（强制npm）
        run: |
          npm config set registry https://registry.npmmirror.com  # 国内镜像
          npm ci --omit=dev  # 严格使用package-lock.json:ml-citation{ref="3" data="citationList"}

      # ███████ 阶段3：构建流程 ███████
      - name: 构建项目
        run: npm run build

      # ███████ 阶段4：部署示例 ███████
      - name: 部署到服务器
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/var/www/app"
