name: Robust Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"

    steps:
    - uses: actions/checkout@v4

    # 关键修复步骤 ████████████████████████████
    - name: 预装基础设施
      run: |
        # 解决依赖关系问题
        sudo apt-get update && sudo apt-get install -y build-essential python3
        # 核武器级清理残留文件
        rm -rf node_modules */node_modules

    - name: 配置 Node.js 18 环境
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    - name: 激活核心包管理器
      run: |
        corepack enable
        corepack prepare pnpm@8 --activate

    - name: 镜像加速（中国大陆优化版）
      run: |
        pnpm config set registry https://registry.npmmirror.com
        pnpm config set store-dir ~/.pnpm-store
        pnpm config set strict-peer-dependencies false

    - name: 安装前端依赖（严格模式）
      working-directory: ./vue-blog-project
      run: |
        pnpm install --frozen-lockfile --prefer-offline
        pnpm store prune  # 清理无效缓存

    - name: 编译生产环境代码
      working-directory: ./vue-blog-project
      run: pnpm build --modern

    # 后续部署步骤保持不变...
