name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ███████ 代码检出与初始化 ██████████████████
    - name: Checkout code
      uses: actions/checkout@v4

    # ███████ Node.js 环境配置 █████████████████
    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'

    # ███████ pnpm 环境修复 ████████████████████
    - name: Enable Corepack
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate

    # ███████ 前端构建阶段 ████████████████████
    - name: Install frontend dependencies
      working-directory: ./vue-blog-project
      run: |
        pnpm install --frozen-lockfile
        pnpm store prune

    - name: Build production assets
      working-directory: ./vue-blog-project
      run: pnpm build

    # ███████ 服务器部署阶段 ██████████████████
    - name: Setup SSH Environment
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
        chmod 600 ~/.ssh/github_actions_key
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Install Rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Deploy with Rsync
      run: |
        rsync -avz --progress --delete \
          -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
          --exclude='node_modules/' \
          --exclude='.git/' \
          --exclude='.github/' \
          --exclude='.env*' \
          ./vue-blog-project/dist/ \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/default/
