name: Z-Blog 全栈项目自动化部署

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Node.js 环境配置████████████████████████
    - name: 配置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
        cache-dependency-path: './vue-blog-project/pnpm-lock.yaml'

    # 包管理器初始化████████████████████████
    - name: 启用 Corepack
      run: corepack enable

    - name: 强制安装 pnpm
      run: |
        npm install -g pnpm@8 --registry=https://registry.npmmirror.com
        echo "全局路径: $(npm root -g)"  # 验证安装位置

    # 前端构建流程██████████████████████████
    - name: 生成锁文件
      working-directory: ./vue-blog-project
      run: pnpm install --lockfile

    - name: 安装依赖
      working-directory: ./vue-blog-project
      run: pnpm install --frozen-lockfile

    - name: 编译生产代码
      working-directory: ./vue-blog-project
      run: pnpm build

    # 后续部署步骤保持不变...
