jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: './vue-blog-project/package-lock.json'

    - name: Validate Lock Files
      working-directory: ./vue-blog-project
      run: |
        echo "当前目录：$(pwd)"
        ls -la  # 列出文件确认锁文件存在

    - name: Install Dependencies
      working-directory: ./vue-blog-project
      run: npm ci  # 使用 package-lock.json 精确安装

    - name: Build Project
      working-directory: ./vue-blog-project
      run: npm run build
