name: Z-Blog 全栈自动部署

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ██ 代码检出 █████████████████████████████████
    - uses: actions/checkout@v4

    # ██ 动态包管理器检测 █████████████████████████
    - name: 智能检测包管理器
      id: detect-pm
      working-directory: ./vue-blog-project
      run: |
        # 检测锁文件类型
        if [ -f "pnpm-lock.yaml" ]; then
          PM="pnpm"
          LOCKFILE="pnpm-lock.yaml"
        elif [ -f "yarn.lock" ]; then
          PM="yarn" 
          LOCKFILE="yarn.lock"
        elif [ -f "package-lock.json" ]; then
          PM="npm"
          LOCKFILE="package-lock.json"
        else
          echo "未检测到锁文件，生成 pnpm 锁文件..."
          pnpm install --lockfile-only
          PM="pnpm"
          LOCKFILE="pnpm-lock.yaml"
        fi

        # 输出检测结果
        echo "使用包管理器: $PM"
        echo "lockfile=./vue-blog-project/$LOCKFILE" >> $GITHUB_OUTPUT
        echo "pm=$PM" >> $GITHUB_OUTPUT

    # ██ Node.js 环境配置 ███████████████████████
    - name: 配置 Node.js 环境
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: ${{ steps.detect-pm.outputs.pm }}
        cache-dependency-path: ${{ steps.detect-pm.outputs.lockfile }}

    # ██ 包管理器安装 ██████████████████████████
    - name: 安装检测到的包管理器
      if: steps.detect-pm.outputs.pm != 'npm'
      run: |
        case "${{ steps.detect-pm.outputs.pm }}" in
          pnpm)
            npm install -g pnpm@8
            ;;
          yarn)
            npm install -g yarn@1
            ;;
        esac

    # ██ 前端依赖安装与构建 █████████████████████
    - name: 安装前端依赖
      working-directory: ./vue-blog-project
      run: |
        case "${{ steps.detect-pm.outputs.pm }}" in
          pnpm)
            pnpm install --frozen-lockfile
            ;;
          yarn)
            yarn install --frozen-lockfile
            ;;
          npm)
            npm ci
            ;;
        esac

    - name: 编译生产代码
      working-directory: ./vue-blog-project
      run: |
        case "${{ steps.detect-pm.outputs.pm }}" in
          pnpm)
            pnpm build
            ;;
          yarn)
            yarn build
            ;;
          npm)
            npm run build
            ;;
        esac

    # ██ 服务器部署 ████████████████████████████
    - name: 配置 SSH 通道
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: 增量文件同步
      run: |
        rsync -avz --progress \
          --exclude=.git \
          --exclude=node_modules \
          --include="vue-blog-project/dist/**" \
          -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }}" \
          ./ \
          ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/var/www/z-blog/
