name: 部署到服务器

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置SSH环境
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          # 注入SSH私钥并确保格式正确
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/github_actions_key
          chmod 600 ~/.ssh/github_actions_key
          # 添加服务器指纹（生产环境建议使用固定指纹）
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: 同步文件到服务器
        run: |
          rsync -avz --progress --delete \
            --exclude='.git' \
            --exclude='.env' \
            --exclude='node_modules/' \
            --exclude='*.log' \
            --exclude='.github/workflows/' \
            -e "ssh -i ~/.ssh/github_actions_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
            $GITHUB_WORKSPACE/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }}:/www/wwwroot/egg-blog/

      - name: 验证部署结果
        run: |
          ssh -i ~/.ssh/github_actions_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SERVER_IP }} \
            "cd /www/wwwroot/egg-blog && git rev-parse HEAD && ls -l"
