name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PNPM_VERSION: "8.15.6"  # 精确锁定版本

    steps:
    # ███████ 第 1 阶段：基础环境配置 ███████████
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Node.js 20.x + pnpm
      uses: pnpm/action-setup@v2  # 使用官方推荐方式
      with:
        node-version: 20.x
        pnpm-version: ${{ env.PNPM_VERSION }}
        run_install: false

    # ███████ 第 2 阶段：依赖安装与构建 ███████
    - name: 安装前端依赖
      working-directory: ./frontend
      run: |
        pnpm install --frozen-lockfile --ignore-scripts
        echo "依赖存储路径: $(pnpm store path)"

    - name: 构建项目
      working-directory: ./frontend
      run: pnpm build
      env:
        NODE_ENV: production

    # ███████ 第 3 阶段：部署优化 ███████████
    - name: 验证构建产物
      run: |
        ls -lh ./frontend/dist
        [ -f ./frontend/dist/index.html ] || (echo "构建产物缺失！"; exit 1)

    - name: 安全部署到服务器
      uses: easingthemes/ssh-deploy@v4  # 更可靠的同步方案
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ${{ secrets.SSH_USER }}
        REMOTE_PORT: 22
        SOURCE: "./frontend/dist/"
        TARGET: "/var/www/production"
        ARGS: "-avz --chmod=755 --delete"
        DEBUG: "true"
